services:
  db-mysql:
    image: mysql:5.7.40
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_DATABASE=hoidanit
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3308:3306"
